version: 0.2

phases:
  install:
    commands:
      - echo Installing system dependencies...
      - sudo yum update -y
      - sudo yum install -y python3-pip python3-dev libpq-dev
      - echo Installing Python dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running tests...
      - python manage.py test
  build:
    commands:
      - echo Collecting static files...
      - python manage.py collectstatic --noinput
      # Include any additional build commands here
artifacts:
  files:
    - '**/*'
  base-directory: 'path/to/collectstatic/output/directory'